language: python
python: 2.7
env:
  - DJANGO_VERSION=1.7.*
  - DJANGO_VERSION=1.8.*
  - DJANGO_VERSION=1.9.*
install:
  - pip install django==$DJANGO_VERSION
  - python setup.py install
script:
  - ./runtests.py
sudo: false
